### ISSUE TITLE
Variables values with dashes

### ISSUE THREAD

**Issue by air3ijai** [fabiocaccamo/create-matrix-action#7]
I'm checking the actions with the values containing dashes and in some cases value is trimmed

<img width="990" alt="Image" src="https://github.com/user-attachments/assets/a824f3bc-b32f-4b45-8fa4-f5006f4d3b0e" />

```yaml
name: Matrix
on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Create matrix
        id: create_matrix
        uses: fabiocaccamo/create-matrix-action@v4
        with:
          matrix: |
            python-version {3.8-1},              command {python3 --version}
            python-version {3.9-2.1},            command {python3 --version}
            python-version {custom-3.10},        command {python3 --version}
            python-version {3.11-custom},        command {python3 --version}
            python-version {custom-3.12-custom}, command {python3 --version}
    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}

  test:
    needs: prepare
    runs-on: ubuntu-latest
    name: ${{ matrix.python-version}}
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Debug matrix
        run: |
          echo "Python version: ${{ matrix.python-version }} / Command: ${{ matrix.command }}"
```
